package dev.frendli;

/**
 * A token - the smallest unit used to create an abstract
 * syntax tree (AST) once generated by the scanner/lexer.
 */
public class Token {
    public final TokenType type;        // The type of token
    public final String lexeme;         // The string of characters making up the token
    public final Object literal;        // The value represented (e.g. of NUMBERs or TEXTs. IDENTIFIERS are null.)
    public final int line;              // The line on which the token appeared in the source code

    public Token(TokenType type, String lexeme, Object literal, int line) {
        this.type = type;
        this.lexeme = lexeme;
        this.literal = literal;
        this.line = line;
    }

    @Override
    public String toString() {
        return type + " " + lexeme + " " + literal;
    }
}
