package dev.frendli;

/**
 * A token - the smallest unit used to create an abstract
 * syntax tree (AST) once generated by the scanner/lexer.
 */
public class Token {
    /**
     * The type of token.
     */
    public final TokenType type;
    /**
     * The sequence of characters making up the token.
     */
    public final String lexeme;
    /**
     * The value represented.
     * (E.g. a double for NUMBER types or a string for TEXT types.
     * Token types without an association to a value use null.)
     */
    public final Object literal;
    /**
     * The line on which the token appeared in the source code.
     */
    public final int line;

    public Token(TokenType type, String lexeme, Object literal, int line) {
        this.type = type;
        this.lexeme = lexeme;
        this.literal = literal;
        this.line = line;
    }

    @Override
    public String toString() {
        return type + " " + lexeme + " " + literal;
    }
}
